[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run prisma:generate && npm run prisma:migrate && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

